# Generated by Django 3.1.7 on 2021-04-01 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210401_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
