# Generated by Django 3.1.7 on 2021-04-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210401_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.list'),
        ),
    ]
